export enum Status {
  ACTIVATED = 'ACTIVATED',
  DESACTIVATED = 'DESACTIVATED',
  SUSPENDED = 'SUSPENDED',
  REMOVED = 'REMOVED',
  CLOSED = 'CLOSED',
  VERIFIED = 'VERIFIED',
  UNVERIFIED = 'UNVERIFIED',
}
